config/routes.rb
 Rails.application.routes.draw do

  root 'home#index'

  #resources :users do
    resources :myalbums do 
  	resources :pictures
  	end 
  #end
#added tag code

get 'tags/:tag', to: 'pictures#index', as: :tag

  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myalbum.rb
class Myalbum < ApplicationRecord
  belongs_to :user
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures 
  validates :name, presence: true 
  validates :description, presence: true 
end

app/models/picture.rb
class Picture < ApplicationRecord
  # belongs_to :user
    belongs_to :myalbum
    has_attached_file :photo, :styles => { :small => "50x50>"}
    validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  #added tag code
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

    def self.tagged_with(name)
    Tag.find_by!(name: name).articles
    end

  #def self.tag_counts
    #Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  #end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings, dependent: :destroy
    has_many :pictures, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :myalbums
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

   if user_signed_in?
     	redirect_to myalbums_path
     else
  	    redirect_to user_session_path
     end

  end
end
 

app/controllers/myalbums_controller.rb
class MyalbumsController < ApplicationController
def new
  @myalbum =Myalbum.new 
  @myalbum.pictures.new
  #@myalbum = Myalbum.find(params[:id])
  #@myalbum.pictures.build
end

def create
  @myalbum = current_user.myalbums.new(myalbum_params)
  
  if @myalbum.save
    redirect_to @myalbum
  else
    render 'new'
  end
end

def index
    @myalbum = current_user.myalbums
end

def show
@myalbum = Myalbum.find(params[:id])
end

def edit
  @myalbum = Myalbum.find(params[:id])
end

  def destroy
      @myalbum = Myalbum.find(params[:id])
      @myalbum.destroy

      redirect_to myalbums_path
  end

  def update
    @myalbum = Myalbum.find(params[:id])
      if @myalbum.update(myalbum_params)
      redirect_to @myalbum
      else
      render 'edit'
      end
  end
end

private
  def myalbum_params
    params.require(:myalbum).permit(:name, :description, pictures_attributes: [:photo] )
  end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show

  end

  # GET /albums/new
  def new

    debugger
    @photo = Photo.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    debugger
    @photo = Photo.new(photo_params)
    respond_to do |format|
      debugger
      if @photo.save
        debugger
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

def new
 @myalbum = Myalbum.find(params[:myalbum_id])
end

  def create
    @myalbum = Myalbum.find(params[:myalbum_id])
    @picture = @myalbum.pictures.new(picture_params)
      if @picture.save
        redirect_to myalbum_path(@myalbum)
      end
  end

  def destroy
    @myalbum = Myalbum.find(params[:myalbum_id])
    #@picture = current_user.myalbums.picture_path(params[:id])
    @picture = @myalbum.pictures.find(params[:id])
    #remove_image_at_index(params[:id].to_i)
    @picture.destroy
    redirect_to myalbum_path(@myalbum)
  end

  def show
    @myalbum = Myalbum.find(params[:myalbum_id])
     @picture = @myalbum.pictures.find_by(params[:id])
    #@picture = Picture.where(album_id: @myalbum.id)
    redirect_to myalbum_picture_path(@myalbum,@picture)
  end

  def index
    #@picture = Picture.all

    #added tag code
    #@picture =  if params[:tag]
    #@myalbum = Myalbum.find(params[:myalbum_id])
    if params[:tag]
    @pictures = Picture.tagged_with(params[:tag])
    else
      Picture.all
    end
  end

  private
    def picture_params
      params.require(:picture).permit(:photo, :tag_list)
    end

  #added delete code
    #def remove_image_at_index(index)
       #remain_images = @myalbum.pictures
     #deleted_image = remain_images.delete_at(index)
     #deleted_image.try(:remove!)
   #end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/myalbums_helper.rb
module MyalbumsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
  <% if user_signed_in? %>
  <p>Hello, <%=current_user.name %> - <%= link_to "sign_out", destroy_user_session_path, :method => 'delete' %></p>

  <br>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/myalbums/_form.html.erb
<%= form_for @myalbum, :html => { :multipart => true } do |f| %>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :DESCRIPTION %><br>
    <%= f.text_field :description %>
  </p>

 <p>
     <%= f.file_field :photo %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/myalbums/edit.html.erb
<h1>Edit myalbum</h1>
<%#= render 'form' %>
<%= form_for @myalbum, :html => { :multipart => true } do |f| %>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :DESCRIPTION %><br>
    <%= f.text_field :description %>
  </p>

 <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', myalbums_path %>

app/views/myalbums/index.html.erb
<h1>Listing Albums</h1>
 <%= link_to 'New Album', new_myalbum_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @myalbum.each do |myalbum| %>
    <tr>
      <td><%= myalbum.name %></td>
      <td><%= myalbum.description %></td>

       <%# @myalbum.pictures.each do |img| %>
       <% if !@pictures.blank? %>
      <td> <%#= image_tag pictures.photo.url %></td>
  <% @myalbum.pictures.each do |img| %>
     <td><%= image_tag img.photo.url %></td>
  <% end %>
      <%end%>

      <td><%= link_to 'Show', myalbum_path(myalbum) %></td>
      <td><%= link_to 'Edit', edit_myalbum_path(myalbum) %></td>
      <td><%= link_to 'Destroy', myalbum_path(myalbum),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
   
    </tr>
  <% end %>
</table>

app/views/myalbums/new.html.erb
<h1>NEW MYALBUM</h1>
 
<%#= render 'form' %>
 <%= form_for @myalbum, :html => { :multipart => true } do |f| %>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :DESCRIPTION %><br>
    <%= f.text_field :description %>
  </p>
<p>ADD YOUR PHOTO HERE</p>

  <%= f.fields_for :pictures do |d| %>
    <%#= d.file_field :photo, multiple: true %>
    <%= d.file_field :photo %>
  <% end %>

  <p>
    <%= f.submit %>
    <%# debugger %>
  </p>

<% end %>

<%= link_to 'All Myalbums', myalbums_path %>

<%#= form_for([@myalbum, @myalbum.pictures.build]) do |f| %>

 <% @myalbum.pictures.each do |picture| %>

  <td><%= image_tag picture.photo.url %></td>

<%#= link_to 'Delete Picture', myalbum_picture_path(@myalbum, picture), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/myalbums/show.html.erb
<p>
  <strong>NAME:</strong>
  <%= @myalbum.name %>
</p>

<p>
  <strong>DESCRIPTION:</strong>
  <%= @myalbum.description %>
</p>
<%#= image_tag @myalbum.myalbum_photo.first.photo.url %>
 
<%= link_to 'Back', myalbums_path %>
<%= link_to 'Edit', edit_myalbum_path(@myalbum) %>
<%= link_to 'Destroy', myalbum_path(@myalbum),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>


<%#= link_to 'Add Photo to Myalbum', new_myalbum_picture_path(@myalbum) %><br />
<%#= link_to 'Show Myalbum', myalbum_pictures_path(@myalbum) %><br />
  <% @myalbum.pictures.each do |picture| %>

  <td><%= image_tag picture.photo.url %></td>
 <%#= link_to 'Delete Picture', 
                         myalbum_picture_path(@myalbum, @pictures), 
                         method: :delete,
                         data: { confirm: 'Are you sure?' } %> 
<%= link_to 'Delete Picture', myalbum_picture_path(@myalbum, picture), method: :delete, data: { confirm: 'Are you sure?' } %>
Tags: <%#= myalbum_picture_path.tag_list(@myalbum, @pictures) %>
<%= raw picture.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>

<% end %>
  
<%= form_for([@myalbum, @myalbum.pictures.build]) do |f| %>
    <p>ADD YOUR PHOTO HERE</p>
    <p>
      <%= f.file_field :photo %>
    </p>

    <p>
        <%= f.label :tag_list, "Tags (separated by commas)" %><br />
        <%= f.text_field :tag_list %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/pictures/index.html.erb
<% @picture.each do |f| %>
<%= image_tag f.photo.url %>

<% end %>

<%#added tag code %>
<p>
<%#= tag_cloud Picture.tag_counts%>
</p>
<p>
<%= raw picture.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
</p>

<td><%= link_to 'Back to Myalbum', myalbums_path(@myalbum) %></td>

app/views/pictures/new.html.erb
<%= form_for([@myalbum, @myalbum.pictures.build]) do |f| %>
<p><h1>ADD YOUR PHOTO HERE</h1></p>
 <p>
    <%= f.file_field :photo %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>